apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-essentials.fullname" . }}
  labels:
    {{- include "home-essentials.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "home-essentials.selectorLabels" . | nindent 4 }}
---
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "home-essentials.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "home-essentials.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "home-essentials.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
