apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-essentials
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AbuEbunoluwa/Home-Essentials.git
    targetRevision: main
    path: helm/home-essentials
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
