image:
  repository: 624782989130.dkr.ecr.us-east-1.amazonaws.com/home-essentials
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

serviceMonitor:
  enabled: false

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "500m"

db:
  host: "postgres-service"
  name: "homeessentials"
  user: "postgres"
  password: "postgres"
  port: "5432"
